DirectoryPath: public
IgnoreDirectoryMissingTrailingSlash: true
CheckExternal: false
IgnoreAltMissing: true
IgnoreEmptyHref: true
IgnoreInternalURLs:
  # Temporal ignores

  # Deprecated and removed resources
  - /docs/2.15/authentication-providers/azure-ad-pod-identity/
  - /docs/2.15/authentication-providers/aws-kiam/
  # Renamed pages
  - /docs/2.15/operate/events/
