DirectoryPath: public
IgnoreDirectoryMissingTrailingSlash: true
CheckExternal: false
IgnoreAltMissing: true
IgnoreEmptyHref: true
IgnoreInternalURLs:
  # Temporal ignores
  - /docs/2.16/scalers/nsq/
  # Deprecated and removed resources

  # Renamed pages
