DirectoryPath: public
IgnoreDirectoryMissingTrailingSlash: true
CheckExternal: false
IgnoreAltMissing: true
IgnoreEmptyHref: true
IgnoreInternalURLs:
  - /docs/2.14/scalers/splunk/
  - /docs/2.14/scalers/dynatrace/
