DirectoryPath: public
EnforceHTTPS: true
EnforceHTML5: true
IgnoreDirectoryMissingTrailingSlash: true
CheckExternal: false
IgnoreAltMissing: true
IgnoreEmptyHref: true
IgnoreURLs:
  # Temporal ignores
  # Deprecated and removed resources
  # Renamed pages
  - /docs/2.18/scalers/splunk-observability.md/
