# Adapted from @chalin's work on https://github.com/chalin/docsy-starter

name: Links

on:
  merge_group:
  pull_request:
  push: { branches: [main] }

jobs:
  build-and-check-links:
    name: BUILD and CHECK LINKS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .nvmrc
          cache: npm

      - run: npm install --omit=optional

      - run: npm run check:links

